name: Daily Adecco Apply

on:
  schedule:
    # 毎日 日本時間 08:00 (UTC 23:00) に実行
    - cron: '0 23 * * *'
  workflow_dispatch: # 手動ボタン用

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          ADEKO_ID: ${{ secrets.ADEKO_ID }}
          ADEKO_PASS: ${{ secrets.ADEKO_PASS }}
        run: python main.py
